---
- name: install rabbitmq
  hosts: controllers
  tasks:
  - name: install rabbitmq-server package
    yum:
      name: rabbitmq-server
      state: installed

  - name: set rabbitmq-server service enabled and started
    service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: register rabbitmq user 'openstack'
    rabbitmq_user:
      user: openstack
      password: "{{ openstack.rabbitmq.user_pass }}"
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present
