---
- name: install mariadb
  hosts: controllers
  tasks:
  - name: install packages
    yum:
      name: "{{ item }}" 
      state: installed
    with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL
    - expect

  - name: put config of mariadb
    template:
      src: openstack.cnf.j2
      dest: /etc/my.cnf.d/openstack.cnf
    register: reg_config_mariadb

  - name: start and enable mariadb
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: restart mariadb
    service:
      name: mariadb
      state: restarted
    when: reg_config_mariadb is changed

  - name: check mariadb's root user is protected with password
    shell: mysql -uroot -e "show databases;"
    changed_when: false
    failed_when: false
    register: reg_show_databases
  
  - name: execute mysql_secure_installation
    script: mysql_secure_installation.sh {{ openstack.mariadb.root_db_pass }}
    when:
    - reg_show_databases.rc == 0
