---
- name: install neutron compute
  hosts: computes
  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset

  - name: put neutron config from template
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    register: reg_neutron_template
    with_items:
    - src: neutron-compute.conf.j2
      dest: /etc/neutron/neutron.conf
    - src: linuxbridge_agent-compute.ini.j2
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini

  - name: put config to load br_netfilter
    copy:
      src: br_netfilter.conf
      dest: /etc/modules-load.d/br_netfilter.conf

  - name: load br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: start and enable neutron controller
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
    - neutron-linuxbridge-agent

  - name: restart neutron controller
    service:
      name: "{{ item }}"
      state: restarted
    when: reg_neutron_template is changed
    with_items:
    - neutron-linuxbridge-agent
